"""Agent-native project surface: ``AGENTS.md`` and its mirrors (brief §9).

Generated projects are written for agents as much as for people. The rule
from the brief: **AGENTS.md is invariants, not description.** Not "this
folder has tools" but "*never* call a network provider inside a
``Sensitive`` scope; add tools only in ``app/tools/``; verify with
``ack check``".

One body, four surfaces — ``AGENTS.md``, a ``CLAUDE.md`` symlink,
``.cursor/rules/`` and ``.github/copilot-instructions.md`` — so an agent
finds the same invariants whichever door it comes through.

Everything written here is deterministic: no timestamps, no absolute
paths, sorted iteration (invariant 4).

Example:
    >>> body = agent_instructions(project_name="demo", blueprint="voice-care",
    ...     pack="healthcare", model_primary="ollama:gemma4:e4b",
    ...     egress="device", redactor="healthcare.phi", capabilities=["voice"])
    >>> "NEVER" in body and "ack check" in body
    True
"""

from __future__ import annotations

from pathlib import Path

from agenticcarekit import __version__
from agenticcarekit.kernel.contracts import AckConfig

__all__ = [
    "agent_instructions",
    "render_ack_toml",
    "write_agent_surface",
    "write_ack_toml",
    "try_git_init",
]

_KNOWN_TABLES = ("project", "model", "policy", "capabilities")


def agent_instructions(
    *,
    project_name: str,
    blueprint: str,
    pack: str,
    model_primary: str,
    egress: str,
    redactor: str | None,
    capabilities: list[str] | tuple[str, ...],
    model_fallback: str | None = None,
) -> str:
    """The shared invariant body written into all four agent surfaces."""
    caps = ", ".join(capabilities) if capabilities else "none enabled"
    fallback = model_fallback or "none — the primary is the only provider"
    red = redactor or "none declared"
    return f"""# {project_name} — agent instructions

Generated by agenticcarekit {__version__} from the `{blueprint}` blueprint.
This project is **decision support only**: documentation, navigation,
accessibility, triage routing, education. **Not diagnosis. Not treatment.**
Synthetic or public data only.

## Invariants

These are not preferences. A change that violates one is wrong even if the
tests pass.

1. **NEVER** pass a value out of a `Sensitive[...]` box by hand. The only
   sanctioned path to a provider is `value.unwrap_for(provider, policy)`.
   `dangerously_reveal()` is greppable on purpose — every use is reviewed.
2. **NEVER** send un-redacted PHI to a `public-cloud` provider. This
   project declares `egress = "{egress}"` and redactor `{red}`. Widening
   egress is a deliberate edit to `ack.toml`, never a workaround in code.
3. **NEVER** infer a model capability. If the model lacks a modality the
   run fails at startup with an E2xx code naming the models that have it.
   Do not add a fallback that silently degrades.
4. **ALWAYS** add tools in `app/tools/`, one file per tool, decorated with
   `@tool(permissions=..., mock=...)`. A tool without a mock fails at
   import with **E502** — the mock is what makes `ack demo --offline` real.
5. **ALWAYS** put prompts in `.md` files. Never a string literal in code.
6. **ALWAYS** verify with `ack check` before claiming a change works. It
   runs lint plus a fast selftest and finishes in under 30 seconds.
7. **NEVER** add telemetry, analytics, or a phone-home update check.
8. `ack.toml` is the source of truth for blueprint, model, policy and
   capabilities. Edit it, then run `ack sync` — do not hand-edit generated
   files and expect them to survive.

## This project

| Key | Value |
|---|---|
| blueprint | `{blueprint}` |
| pack | `{pack}` |
| primary model | `{model_primary}` |
| fallback | `{fallback}` |
| egress | `{egress}` |
| redactor | `{red}` |
| capabilities | {caps} |

## Commands

| Task | Command |
|---|---|
| environment check | `ack doctor --json` |
| verification loop | `ack check --json` |
| project description | `ack manifest --json` |
| run the demo offline | `ack demo --offline` |
| score against goldens | `ack eval --json` |
| explain an error code | `ack explain E203 --json` |
| reconcile the tree | `ack sync` |

Every command accepts `--json`. Prefer it: the output schema is stable and
documented in `spec/`.

## Where things live

- `app/` — your code. Yours to edit, never regenerated over.
- `prompts/` — prompt `.md` files. Change behaviour here, not in logic.
- `ack.toml` — declarative project state.
- `AGENTS.md` — this file. `CLAUDE.md` is a symlink to it.
"""


def write_agent_surface(dest: Path, body: str) -> list[str]:
    """Write ``AGENTS.md`` and its three mirrors. Returns paths, sorted.

    ``CLAUDE.md`` is a symlink where the platform allows one and a copy
    where it does not — the content is identical either way.
    """
    written: list[str] = []
    dest.mkdir(parents=True, exist_ok=True)

    agents = dest / "AGENTS.md"
    agents.write_text(body, encoding="utf-8")
    written.append("AGENTS.md")

    claude = dest / "CLAUDE.md"
    if claude.exists() or claude.is_symlink():
        claude.unlink()
    try:
        claude.symlink_to("AGENTS.md")
    except (OSError, NotImplementedError):  # pragma: no cover - Windows without privilege
        claude.write_text(body, encoding="utf-8")
    written.append("CLAUDE.md")

    cursor = dest / ".cursor" / "rules"
    cursor.mkdir(parents=True, exist_ok=True)
    (cursor / "agenticcarekit.mdc").write_text(
        "---\n"
        "description: agenticcarekit project invariants (privacy boundary, tools, prompts)\n"
        "alwaysApply: true\n"
        "---\n\n" + body,
        encoding="utf-8",
    )
    written.append(".cursor/rules/agenticcarekit.mdc")

    gh = dest / ".github"
    gh.mkdir(parents=True, exist_ok=True)
    (gh / "copilot-instructions.md").write_text(body, encoding="utf-8")
    written.append(".github/copilot-instructions.md")

    return sorted(written)


def render_ack_toml(cfg: AckConfig) -> str:
    """``AckConfig.to_toml()`` plus any user tables the config carries.

    Contract 5 says unknown keys are preserved — ``ack sync`` must never
    destroy a user's or an agent's edits. ``to_toml()`` only knows the four
    canonical tables, so anything else in ``raw`` is re-emitted after them,
    sorted, byte-identically.
    """
    out = cfg.to_toml()
    extras = {k: v for k, v in (cfg.raw or {}).items() if k not in _KNOWN_TABLES}
    if not extras:
        return out
    lines = [out.rstrip("\n"), ""]
    for table in sorted(extras):
        value = extras[table]
        if not isinstance(value, dict):
            continue
        lines.append(f"[{table}]")
        for key in sorted(value):
            lines.append(f"{key} = {_toml_value(value[key])}")
        lines.append("")
    return "\n".join(lines)


def _toml_value(value: object) -> str:
    """Minimal deterministic TOML scalar/array rendering.

    Example:
        >>> _toml_value(["a", "b"]), _toml_value(True), _toml_value(3)
        ('["a", "b"]', 'true', '3')
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    return '"' + str(value).replace('"', '\\"') + '"'


def write_ack_toml(dest: Path, cfg: AckConfig) -> str:
    """Write ``ack.toml`` deterministically. Returns the relative path."""
    (dest / "ack.toml").write_text(render_ack_toml(cfg), encoding="utf-8")
    return "ack.toml"


def try_git_init(dest: Path, *, runner: object | None = None) -> str | None:
    """``git init`` the generated project when git is available.

    Returns a short status string, or None when git is not installed. A
    missing git is not an error — the project works without it.
    """
    import shutil
    import subprocess

    if (dest / ".git").is_dir():
        return "already a git repository"
    git = shutil.which("git")
    if not git:
        return None
    try:
        proc = subprocess.run(  # noqa: S603 - fixed argv
            [git, "init", "-q"], cwd=dest, capture_output=True, text=True, timeout=10, check=False
        )
    except (OSError, subprocess.SubprocessError):  # pragma: no cover - defensive
        return None
    return "initialised a git repository" if proc.returncode == 0 else None
