# Decision support only — not diagnosis, not treatment. Synthetic/public data only.
"""Agentic administrative copilot — generated by agenticcarekit.

This package is yours: ejectable, no callbacks into the generator. It
imports ``agenticcarekit`` the same way it would import any other
dependency.
"""
